version: '3'
services:
  filer:
    build: ./docker/apache-php
    ports:
      - 127.0.0.1:80:80
    links:
      - bdd:bdd
    volumes:
      - ./src/:/app/
  bdd:
    image: mariadb:10.0.24
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: site_magento
      MYSQL_PASSWORD: site_magento
      MYSQL_DATABASE: site_magento
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6
    depends_on:
      - bdd
    ports:
      - 127.0.0.1:8080:80
    environment:
      PMA_HOST: bdd
