<h1><?php echo $this->__('Brand List'); ?></h1>

<?php $brandCollection = $this->getBrands();
?>
<?php if ($brandCollection->getSize() > 0): ?>

    <ul>
		<?php foreach ($brandCollection as $_brand): ?>
            <li><a href="<?php echo  Mage::helper('esgi_brand')->getBrandUrl($_brand); ?>" title="<?php echo $this->escapeHtml($_brand->getName()); ?>"><?php echo $_brand->getName(); ?></a></li>
		<?php endforeach; ?>
    </ul>

<?php else: ?>

	<?php echo $this->__('There are no brands to display at this time.'); ?>

<?php endif; ?>