<?php $brand = $this->getCurrentBrand(); ?>
<?php if ($brand): ?>

    <img width="200px" src="<?php echo Mage::helper('esgi_brand')->getImageUrl($brand->getLogo()); ?>" title="<?php echo $brand->getName(); ?>">
	<h1><?php echo $brand->getName(); ?></h1>
	<?php echo $brand->getDescription(); ?>
	<p><a href="<?php echo $this->getUrl('esgi_brand/index/index') ?>" title="<?php echo $this->__('Back to Brand Directory'); ?>"><?php echo $this->__('&laquo; Back to Brand Directory'); ?></a></p>

	<?php $productCollection = $this->getProductCollection(); ?>
	<?php if ($productCollection->count() > 0): ?>

		<h2>Products</h2>
		<ul>
			<?php foreach ($productCollection as $_product): ?>
                <li><a href="<?php echo $this->getUrl('catalog/product/view', array('id' => $_product->getId())); ?>" title="<?php echo $this->escapeHtml($_product->getName()); ?>"><?php echo $_product->getName(); ?></a></li>
			<?php endforeach; ?>
		</ul>

	<?php endif; ?>

<?php endif; ?>

